FROM nginx:1.15.0-alpine

# Removendo a configuração padrão do nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copiando o arquivo de configuração criado e enviando para o nginx
COPY nginx.conf /etc/nginx/conf.d

RUN mkdir /var/www/html -p && touch /var/www/html/index.php
